sudo: required

language: python

services:
  - docker

python:
  - "3.6"

before_install:
- docker pull yyz1989/rdf4j

install:
  - pip install flake8

script:
  - flake8 src tests
  - python setup.py test
