INSERT DATA {

    :Subject rdf:type rdfs:Class .

    :User rdfs:subClassOf :Subject .

    :Group rdf:type rdfs:Class ;
           rdfs:subClassOf :Subject .

    :Organization rdf:type rdfs:Class ;
                  rdfs:subClassOf :Subject .

    :Membership rdf:type rdf:Property .

    :memberOf rdf:type rdf:Property ;
              rdfs:subPropertyOf :Membership .

    :ownerOf rdf:type rdf:Property ;
             rdfs:subPropertyOf :Membership ;
             :implies :memberOf .

    :Resource rdf:type rdfs:Class .

    :Permission rdf:type rdf:Property .

    :Read rdf:type rdf:Property ;
          rdfs:subPropertyOf :Permission .

    :Write rdf:type rdf:Property ;
           rdfs:subPropertyOf :Permission ;
           :implies :Read .

    :Admin rdf:type rdf:Property ;
           rdfs:subPropertyOf :Permission ;
           :implies :Write ,
                    :Read .

    :Repository rdf:type rdfs:Class ;
                rdfs:subClassOf :Resource .

    :Import rdf:type rdfs:Class ;
            rdfs:subClassOf :Resource ;
            rdfs:comment "Collection of data treated as a single block to import" .

    :BFU rdf:type rdfs:Class ;
         rdfs:subClassOf :Resource ;
         rdfs:comment "Bio-Formats Unit" .

    :File rdf:type rdfs:Class ;
          rdfs:subClassOf :Resource ;
          rdfs:comment "A file" .

    :Image rdf:type rdfs:Class ;
           rdfs:subClassOf :Resource ;
           rdfs:comment "Bio-Formats Image" .

    :name rdfs:comment "The name" .

    :complete rdfs:comment "Completed status of a resource. For an import this means whether the user is done uploading. For a BFU it means that its images have been fully imported" .

    :implies rdfs:comment "Property implied by another property" .

    :memberOf rdfs:comment "Subject membership of a subject, where the membership can be of any subject except a user" .

    :inResource rdfs:comment "A resource within a resource" .
}
